title: Benson LEVI
logo:![Head4](https://github.com/Blab2023/DataAnalyst/assets/img/Head4.png)
description: Data scientist proficient in Python programming
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
